### ISSUE TITLE
title

### ISSUE THREAD

**Issue by Linnnnnna** [StormyBytes/MLogWiki#13]
is it possible to bind all oct and corvus with different flag group
1 oct and 1 corvus as one group
（only use 2 logicblock and 1 memorycell）
![QQ浏览器截图20220606180614](https://user-images.githubusercontent.com/63439268/172143254-ad41f410-5bc6-4f62-be08-6eb8ef6e5845.png)

**Comment by sbxte** [comment]
yes

**Comment by Linnnnnna** [comment]
> yes

thx!
